In [1]:
import damask
import numpy as np
import matplotlib.pyplot as plt

In [2]:
config_material = damask.ConfigMaterial()
config_material

material: []

homogenization: {}

phase: {}

In [3]:
config_material['homogenization']['dummy'] = {'N_constituents': 1, 'mechanical': {'type': 'pass'}}

In [4]:
config_material['phase']['A'] = damask.ConfigMaterial.load('config/phase/Fe.yaml')
config_material['phase']['A']['mechanical'] = {}
config_material['phase']['A']['mechanical']['output'] = ['F', 'P', 'F_p', 'F_e', 'L_p', 'O']
config_material['phase']['A']['mechanical']['elastic'] = damask.ConfigMaterial.load('config/phase/mechanical/elastic/Hooke_Fe.yaml')
config_material['phase']['A']['mechanical']['plastic'] = damask.ConfigMaterial.load('config/phase/mechanical/plastic/phenopowerlaw_DP-steel-ferrite.yaml')


config_material['phase']['B'] = damask.ConfigMaterial.load('config/phase/Fe.yaml')
config_material['phase']['B']['mechanical'] = {}
config_material['phase']['B']['mechanical']['output'] = ['F', 'P', 'F_p', 'F_e', 'L_p', 'O']
config_material['phase']['B']['mechanical']['elastic'] = damask.ConfigMaterial.load('config/phase/mechanical/elastic/Hooke_Fe.yaml')
config_material['phase']['B']['mechanical']['plastic'] = damask.ConfigMaterial.load('config/phase/mechanical/plastic/phenopowerlaw_DP-steel-ferrite.yaml')
(config_material['phase']['B']['mechanical']['plastic']['xi_0_sl'][0]) *= 1.5
(config_material['phase']['B']['mechanical']['plastic']['xi_0_sl'][1]) *= 1.5


In [5]:
config_material

material: []

homogenization:
  dummy:
    N_constituents: 1
    mechanical: {type: pass}

phase:
  A:
    references: ['https://en.wikipedia.org/wiki/Iron']
    lattice: cI
    rho: 7874.0
    mechanical:
      output: [F, P, F_p, F_e, L_p, O]
      elastic:
        type: Hooke
        references: ["D.J. Dever, Journal of Applied Physics 43(8):3293-3301, 1972, https://doi.org/10.1063/1.1661710 fit to Tab. II (T_min=25\xC2\xBAC, T_max=880\xC2\xBAC)"]
        C_11: 232100000000.0
        C_11,T: -46780000.0
        C_11,T^2: -57620.0
        C_12: 135900000000.0
        C_12,T: -16950000.0
        C_12,T^2: 1555.0
        C_44: 117000000000.0
        C_44,T: -20470000.0
        C_44,T^2: -281.4
        T_ref: 293.15
      plastic:
        type: phenopowerlaw
        references: ['C.C. Tasan et al., Acta Materialia 81:386-400, 2014, https://doi.org/10.1016/j.actamat.2014.07.071', "U.F. Kocks, Metallurgical and Materials Transactions B 1:1121\xE2\u20AC\u201C1143, 1970, https://doi.org/10.

In [6]:
O_A = damask.Rotation.from_random(10)
O_B = damask.Rotation.from_random(5)
O_A

Quaternions of shape (10,)
[[ 0.26370005 -0.53573492 -0.75558327 -0.26934049]
 [ 0.04264825  0.39284089 -0.55905248  0.72891528]
 [ 0.31932287 -0.65032329  0.00117338 -0.68928306]
 [ 0.10136128 -0.93983123 -0.32521463  0.02604967]
 [ 0.03322311  0.94953552  0.1761616   0.25738224]
 [ 0.06190552  0.82073949  0.09695019 -0.55960259]
 [ 0.2913919   0.00157773  0.57405743  0.76521   ]
 [ 0.22767543  0.46615836  0.19927749 -0.83135357]
 [ 0.72443453 -0.33197453 -0.11411172 -0.59326726]
 [ 0.66868774 -0.06107635 -0.41674479 -0.61273988]]

In [7]:
config_material = config_material.material_add(homogenization='dummy', phase ='A', O=O_A)
config_material = config_material.material_add(homogenization='dummy', phase ='B', O=O_B)
config_material

material:
  - constituents:
      - phase: A
        O: [0.26370004878185715, -0.535734924741531, -0.7555832675394406, -0.2693404917554254]
        v: 1.0
    homogenization: dummy
  - constituents:
      - phase: A
        O: [0.042648247033737575, 0.39284088802733297, -0.5590524820138792, 0.7289152804496329]
        v: 1.0
    homogenization: dummy
  - constituents:
      - phase: A
        O: [0.31932287185465785, -0.6503232931091364, 0.0011733840589975744, -0.6892830631315643]
        v: 1.0
    homogenization: dummy
  - constituents:
      - phase: A
        O: [0.10136127548064099, -0.9398312338577509, -0.3252146346252944, 0.026049666483307386]
        v: 1.0
    homogenization: dummy
  - constituents:
      - phase: A
        O: [0.03322310506958274, 0.9495355173177296, 0.17616159522128072, 0.25738224299819273]
        v: 1.0
    homogenization: dummy
  - constituents:
      - phase: A
        O: [0.06190552319235603, 0.8207394880107814, 0.0969501911057629, -0.5596025906503982]


In [8]:
config_material.save()